module.exports = grammar({
  name: "tcss",

  extras: ($) => [/\s/, $.comment_block, $.comment_line],

  conflicts: ($) => [[$.property_keyword, $.color_keyword]],

  rules: {
    stylesheet: ($) => repeat(choice($.rule_set, $.variable_definition)),

    comment_block: ($) => token(seq("/*", /[^*]*\*+([^/*][^*]*\*+)*/, "/")),

    comment_line: ($) => token(seq("# ", /.*/)),

    selectors: ($) => seq($.selector, repeat(seq(",", $.selector))),

    selector: ($) =>
      prec.left(
        seq(
          $._selector_unit,
          repeat(choice(seq($.combinator, $._selector_unit), $._selector_unit)),
        ),
      ),

    _selector_unit: ($) =>
      choice(
        $.wildcard_selector,
        $.nesting_selector,
        $.class_selector,
        $.id_selector,
        $.pseudo_class_selector,
        $.widget_selector,
      ),

    wildcard_selector: ($) => "*",

    nesting_selector: ($) => "&",

    class_selector: ($) => seq(".", $.class_name),

    id_selector: ($) => seq("#", $.id_name),

    class_name: ($) => /[-a-zA-Z_][-a-zA-Z0-9_]*/,
    id_name: ($) => /[-a-zA-Z0-9_]+/,

    pseudo_class_selector: ($) =>
      seq(
        ":",
        choice(
          "ansi",
          "blur",
          "can-focus",
          "dark",
          "disabled",
          "enabled",
          "even",
          "first-of-type",
          "first-child",
          "focus",
          "focus-within",
          "hover",
          "inline",
          "last-of-type",
          "last-child",
          "light",
          "odd",
        ),
      ),

    widget_selector: ($) => /[a-zA-Z_][a-zA-Z0-9_-]*/,

    combinator: ($) => ">",

    rule_set: ($) => seq($.selectors, $.block),

    block: ($) => seq("{", repeat(choice($.declaration, $.rule_set)), "}"),

    declaration: ($) =>
      seq($.property_name, ":", repeat1($._value), optional($.important), ";"),

    property_name: ($) =>
      choice(
        "align",
        "align-horizontal",
        "align-vertical",
        "background",
        "background-tint",
        "border",
        "border-bottom",
        "border-left",
        "border-right",
        "border-subtitle-align",
        "border-subtitle-background",
        "border-subtitle-color",
        "border-subtitle-style",
        "border-title-align",
        "border-title-background",
        "border-title-color",
        "border-title-style",
        "border-top",
        "box-sizing",
        "color",
        "column-span",
        "constrain",
        "content-align",
        "content-align-horizontal",
        "content-align-vertical",
        "display",
        "dock",
        "grid",
        "grid-columns",
        "grid-gutter",
        "grid-rows",
        "grid-size",
        "hatch",
        "height",
        "keyline",
        "layer",
        "layers",
        "layout",
        "link-background",
        "link-background-hover",
        "link-color",
        "link-color-hover",
        "link-style",
        "link-style-hover",
        "links",
        "margin",
        "margin-bottom",
        "margin-left",
        "margin-right",
        "margin-top",
        "max-height",
        "max-width",
        "min-height",
        "min-width",
        "offset",
        "offset-x",
        "offset-y",
        "opacity",
        "outline",
        "outline-bottom",
        "outline-left",
        "outline-right",
        "outline-top",
        "overflow",
        "overflow-x",
        "overflow-y",
        "overlay",
        "padding",
        "padding-bottom",
        "padding-left",
        "padding-right",
        "padding-top",
        "pointer",
        "position",
        "row-span",
        "scrollbar-background",
        "scrollbar-background-active",
        "scrollbar-background-hover",
        "scrollbar-color",
        "scrollbar-color-active",
        "scrollbar-color-hover",
        "scrollbar-corner-color",
        "scrollbar-gutter",
        "scrollbar-size",
        "scrollbar-size-horizontal",
        "scrollbar-size-vertical",
        "scrollbar-visibility",
        "text-align",
        "text-opacity",
        "text-overflow",
        "text-style",
        "text-wrap",
        "tint",
        "visibility",
        "width",
      ),

    important: ($) => /!\s*important/,

    _value: ($) =>
      choice(
        $.property_keyword,
        $.color_keyword,
        $.numeric_value,
        $.color_value,
        $.function_call,
        $.variable,
        $.plain_value,
      ),

    property_keyword: ($) =>
      choice(
        "absolute",
        "alias",
        "ascii",
        "auto",
        "backslash",
        "blank",
        "blink",
        "block",
        "bold",
        "border-box",
        "both",
        "bottom",
        "cell",
        "center",
        "clip",
        "content-box",
        "copy",
        "cross",
        "crosshair",
        "dashed",
        "default",
        "disabled",
        "double",
        "e-resize",
        "ellipsis",
        "enabled",
        "end",
        "ew-resize",
        "fold",
        "grab",
        "grabbing",
        "grid",
        "heavy",
        "help",
        "hidden",
        "hkey",
        "horizontal",
        "inflect",
        "initial",
        "inner",
        "italic",
        "justify",
        "left",
        "middle",
        "move",
        "n-resize",
        "ne-resize",
        "nesw-resize",
        "no-drop",
        "none",
        "not-allowed",
        "nowrap",
        "ns-resize",
        "nw-resize",
        "nwse-resize",
        "outer",
        "panel",
        "pointer",
        "progress",
        "relative",
        "reverse",
        "right",
        "round",
        "s-resize",
        "screen",
        "scroll",
        "se-resize",
        "slash",
        "solid",
        "stable",
        "start",
        "strike",
        "sw-resize",
        "tall",
        "text",
        "thick",
        "top",
        "transparent",
        "underline",
        "vertical",
        "vertical-text",
        "visible",
        "vkey",
        "w-resize",
        "wait",
        "wide",
        "wrap",
        "x",
        "y",
        "zoom-in",
        "zoom-out",
      ),

    color_keyword: ($) =>
      choice(
        "aliceblue",
        "ansi_black",
        "ansi_blue",
        "ansi_bright_black",
        "ansi_bright_blue",
        "ansi_bright_cyan",
        "ansi_bright_green",
        "ansi_bright_magenta",
        "ansi_bright_red",
        "ansi_bright_white",
        "ansi_bright_yellow",
        "ansi_cyan",
        "ansi_green",
        "ansi_magenta",
        "ansi_red",
        "ansi_white",
        "ansi_yellow",
        "antiquewhite",
        "aqua",
        "aquamarine",
        "auto",
        "azure",
        "beige",
        "bisque",
        "black",
        "blanchedalmond",
        "blue",
        "blueviolet",
        "brown",
        "burlywood",
        "cadetblue",
        "chartreuse",
        "chocolate",
        "coral",
        "cornflowerblue",
        "cornsilk",
        "crimson",
        "cyan",
        "darkblue",
        "darkcyan",
        "darkgoldenrod",
        "darkgray",
        "darkgreen",
        "darkgrey",
        "darkkhaki",
        "darkmagenta",
        "darkolivegreen",
        "darkorange",
        "darkorchid",
        "darkred",
        "darksalmon",
        "darkseagreen",
        "darkslateblue",
        "darkslategray",
        "darkslategrey",
        "darkturquoise",
        "darkviolet",
        "deeppink",
        "deepskyblue",
        "dimgray",
        "dimgrey",
        "dodgerblue",
        "firebrick",
        "floralwhite",
        "forestgreen",
        "fuchsia",
        "gainsboro",
        "ghostwhite",
        "gold",
        "goldenrod",
        "gray",
        "green",
        "greenyellow",
        "grey",
        "honeydew",
        "hotpink",
        "indianred",
        "indigo",
        "ivory",
        "khaki",
        "lavender",
        "lavenderblush",
        "lawngreen",
        "lemonchiffon",
        "lightblue",
        "lightcoral",
        "lightcyan",
        "lightgoldenrodyellow",
        "lightgray",
        "lightgreen",
        "lightgrey",
        "lightpink",
        "lightsalmon",
        "lightseagreen",
        "lightskyblue",
        "lightslategray",
        "lightslategrey",
        "lightsteelblue",
        "lightyellow",
        "lime",
        "limegreen",
        "linen",
        "magenta",
        "maroon",
        "mediumaquamarine",
        "mediumblue",
        "mediumorchid",
        "mediumpurple",
        "mediumseagreen",
        "mediumslateblue",
        "mediumspringgreen",
        "mediumturquoise",
        "mediumvioletred",
        "midnightblue",
        "mintcream",
        "mistyrose",
        "moccasin",
        "navy",
        "navajowhite",
        "oldlace",
        "olive",
        "olivedrab",
        "orange",
        "orangered",
        "orchid",
        "palegoldenrod",
        "palegreen",
        "paleturquoise",
        "palevioletred",
        "papayawhip",
        "peachpuff",
        "peru",
        "pink",
        "plum",
        "powderblue",
        "purple",
        "red",
        "rosybrown",
        "royalblue",
        "saddlebrown",
        "salmon",
        "sandybrown",
        "seagreen",
        "seashell",
        "sienna",
        "silver",
        "skyblue",
        "slateblue",
        "slategray",
        "slategrey",
        "snow",
        "springgreen",
        "steelblue",
        "tan",
        "teal",
        "thistle",
        "tomato",
        "transparent",
        "turquoise",
        "violet",
        "wheat",
        "white",
        "whitesmoke",
        "yellow",
        "yellowgreen",
      ),

    numeric_value: ($) =>
      token(
        seq(
          optional(/[-+]/),
          choice(
            seq(/[0-9]+/, optional(seq(".", /[0-9]+/))),
            seq(".", /[0-9]+/),
          ),
          optional(choice("%", "fr", "h", "vh", "vw", "w")),
        ),
      ),

    color_value: ($) => /#[0-9a-fA-F]{3,8}/,

    function_call: ($) =>
      seq(
        choice("rgb", "rgba", "hsl", "hsla"),
        "(",
        repeat(seq($._value, optional(","))),
        ")",
      ),

    variable: ($) => /\$[a-zA-Z_-][a-zA-Z0-9_-]*/,

    plain_value: ($) => /\w+/,

    variable_definition: ($) => seq($.variable, ":", $._value, ";"),
  },
});
