/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_SLASH_STAR = 3,
  aux_sym_comment_token2 = 4,
  anon_sym_SLASH = 5,
  anon_sym_COLON = 6,
  anon_sym_SEMI = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_COMMA = 10,
  sym_combinator = 11,
  sym_type_selector = 12,
  anon_sym_DOT = 13,
  aux_sym_class_selector_token1 = 14,
  anon_sym_POUND2 = 15,
  aux_sym_pseudo_class_selector_token1 = 16,
  sym_wildcard_selector = 17,
  sym_parent_reference = 18,
  sym_property_name = 19,
  sym_important = 20,
  sym_value_number = 21,
  sym_value_string = 22,
  anon_sym_rgb = 23,
  anon_sym_rgba = 24,
  anon_sym_hsl = 25,
  anon_sym_hsla = 26,
  anon_sym_LPAREN = 27,
  anon_sym_RPAREN = 28,
  anon_sym_DOLLAR = 29,
  sym_source_file = 30,
  sym_comment = 31,
  sym_variable_declaration = 32,
  sym_rule_set = 33,
  sym_declaration = 34,
  sym_selector = 35,
  sym_class_selector = 36,
  sym_id_selector = 37,
  sym_pseudo_class_selector = 38,
  sym_value_list = 39,
  sym_function_call = 40,
  sym_variable = 41,
  sym_variable_reference = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_rule_set_repeat1 = 44,
  aux_sym_selector_group_repeat1 = 45,
  aux_sym_selector_repeat1 = 46,
  aux_sym_simple_selector_repeat1 = 47,
  aux_sym_value_list_repeat1 = 48,
  aux_sym_function_call_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "# ",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_SLASH] = "/",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [sym_combinator] = "combinator",
  [sym_type_selector] = "type_selector",
  [anon_sym_DOT] = ".",
  [aux_sym_class_selector_token1] = "class_selector_token1",
  [anon_sym_POUND2] = "#",
  [aux_sym_pseudo_class_selector_token1] = "pseudo_class_selector_token1",
  [sym_wildcard_selector] = "wildcard_selector",
  [sym_parent_reference] = "parent_reference",
  [sym_property_name] = "property_name",
  [sym_important] = "important",
  [sym_value_number] = "value_number",
  [sym_value_string] = "value_string",
  [anon_sym_rgb] = "rgb",
  [anon_sym_rgba] = "rgba",
  [anon_sym_hsl] = "hsl",
  [anon_sym_hsla] = "hsla",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOLLAR] = "$",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_variable_declaration] = "variable_declaration",
  [sym_rule_set] = "rule_set",
  [sym_declaration] = "declaration",
  [sym_selector] = "selector",
  [sym_class_selector] = "class_selector",
  [sym_id_selector] = "id_selector",
  [sym_pseudo_class_selector] = "pseudo_class_selector",
  [sym_value_list] = "value_list",
  [sym_function_call] = "function_call",
  [sym_variable] = "variable",
  [sym_variable_reference] = "variable_reference",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_rule_set_repeat1] = "rule_set_repeat1",
  [aux_sym_selector_group_repeat1] = "selector_group_repeat1",
  [aux_sym_selector_repeat1] = "selector_repeat1",
  [aux_sym_simple_selector_repeat1] = "simple_selector_repeat1",
  [aux_sym_value_list_repeat1] = "value_list_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_combinator] = sym_combinator,
  [sym_type_selector] = sym_type_selector,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_class_selector_token1] = aux_sym_class_selector_token1,
  [anon_sym_POUND2] = anon_sym_POUND2,
  [aux_sym_pseudo_class_selector_token1] = aux_sym_pseudo_class_selector_token1,
  [sym_wildcard_selector] = sym_wildcard_selector,
  [sym_parent_reference] = sym_parent_reference,
  [sym_property_name] = sym_property_name,
  [sym_important] = sym_important,
  [sym_value_number] = sym_value_number,
  [sym_value_string] = sym_value_string,
  [anon_sym_rgb] = anon_sym_rgb,
  [anon_sym_rgba] = anon_sym_rgba,
  [anon_sym_hsl] = anon_sym_hsl,
  [anon_sym_hsla] = anon_sym_hsla,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_rule_set] = sym_rule_set,
  [sym_declaration] = sym_declaration,
  [sym_selector] = sym_selector,
  [sym_class_selector] = sym_class_selector,
  [sym_id_selector] = sym_id_selector,
  [sym_pseudo_class_selector] = sym_pseudo_class_selector,
  [sym_value_list] = sym_value_list,
  [sym_function_call] = sym_function_call,
  [sym_variable] = sym_variable,
  [sym_variable_reference] = sym_variable_reference,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_rule_set_repeat1] = aux_sym_rule_set_repeat1,
  [aux_sym_selector_group_repeat1] = aux_sym_selector_group_repeat1,
  [aux_sym_selector_repeat1] = aux_sym_selector_repeat1,
  [aux_sym_simple_selector_repeat1] = aux_sym_simple_selector_repeat1,
  [aux_sym_value_list_repeat1] = aux_sym_value_list_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_combinator] = {
    .visible = true,
    .named = true,
  },
  [sym_type_selector] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_class_selector_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_pseudo_class_selector_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_wildcard_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_parent_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym_important] = {
    .visible = true,
    .named = true,
  },
  [sym_value_number] = {
    .visible = true,
    .named = true,
  },
  [sym_value_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_rgb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rgba] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hsl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hsla] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_rule_set] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_class_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_id_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_pseudo_class_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_value_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_reference] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selector_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_simple_selector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 4,
  [9] = 9,
  [10] = 6,
  [11] = 7,
  [12] = 5,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 24,
  [30] = 21,
  [31] = 23,
  [32] = 20,
  [33] = 26,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 50,
  [52] = 48,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 54,
  [66] = 66,
  [67] = 57,
  [68] = 68,
  [69] = 69,
  [70] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '!', 20,
        '#', 62,
        '$', 87,
        '&', 65,
        '(', 85,
        ')', 86,
        '*', 64,
        '+', 16,
        ',', 46,
        '-', 71,
        '.', 52,
        '/', 41,
        ':', 42,
        ';', 43,
        '>', 47,
      );
      if (lookahead == '\\') SKIP(30);
      if (lookahead == '_') ADVANCE(48);
      if (lookahead == 'h') ADVANCE(56);
      if (lookahead == 'r') ADVANCE(54);
      if (lookahead == '{') ADVANCE(44);
      if (lookahead == '}') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(49);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(11);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(11);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(12);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(12);
      if (lookahead == '\r') SKIP(3);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(17);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(17);
      if (lookahead == '\r') SKIP(7);
      END_STATE();
    case 9:
      if (lookahead == '\n') SKIP(18);
      END_STATE();
    case 10:
      if (lookahead == '\n') SKIP(18);
      if (lookahead == '\r') SKIP(9);
      END_STATE();
    case 11:
      ADVANCE_MAP(
        '!', 20,
        '$', 87,
        ')', 86,
        '+', 16,
        ',', 46,
        '-', 71,
        '.', 28,
        ':', 42,
        ';', 43,
      );
      if (lookahead == '\\') SKIP(2);
      if (lookahead == 'h') ADVANCE(75);
      if (lookahead == 'r') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 12:
      if (lookahead == '#') ADVANCE(61);
      if (lookahead == '&') ADVANCE(65);
      if (lookahead == '*') ADVANCE(64);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '\\') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(50);
      END_STATE();
    case 13:
      if (lookahead == '*') ADVANCE(39);
      END_STATE();
    case 14:
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == '*') ADVANCE(40);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 17:
      if (lookahead == '\\') SKIP(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 18:
      if (lookahead == '\\') SKIP(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 29:
      if (eof) ADVANCE(34);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 30:
      if (eof) ADVANCE(34);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(29);
      END_STATE();
    case 31:
      if (eof) ADVANCE(34);
      if (lookahead == '\n') SKIP(33);
      END_STATE();
    case 32:
      if (eof) ADVANCE(34);
      if (lookahead == '\n') SKIP(33);
      if (lookahead == '\r') SKIP(31);
      END_STATE();
    case 33:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '#', 62,
        '$', 87,
        '&', 65,
        '*', 64,
        ',', 46,
        '.', 51,
        '/', 13,
        ':', 42,
        '>', 47,
      );
      if (lookahead == '\\') SKIP(32);
      if (lookahead == '{') ADVANCE(44);
      if (lookahead == '}') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(33);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(50);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\r') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\\') ADVANCE(36);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(15);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_combinator);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_type_selector);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(49);
      if (lookahead == '-' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_type_selector);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_type_selector);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_class_selector_token1);
      if (lookahead == 'b') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (lookahead == '-' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_class_selector_token1);
      if (lookahead == 'g') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (lookahead == '-' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_class_selector_token1);
      if (lookahead == 'l') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (lookahead == '-' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_class_selector_token1);
      if (lookahead == 's') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (lookahead == '-' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_class_selector_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (lookahead == '-' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_class_selector_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_class_selector_token1);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_class_selector_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_POUND2);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_POUND2);
      if (lookahead == ' ') ADVANCE(35);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_pseudo_class_selector_token1);
      if (lookahead == '-' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_wildcard_selector);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_parent_reference);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_property_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_important);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_value_number);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_value_number);
      if (lookahead == '%') ADVANCE(68);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_value_number);
      if (lookahead == '%') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_value_string);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_value_string);
      if (lookahead == 'b') ADVANCE(78);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_value_string);
      if (lookahead == 'g') ADVANCE(72);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_value_string);
      if (lookahead == 'l') ADVANCE(82);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_value_string);
      if (lookahead == 's') ADVANCE(74);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_value_string);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_rgb);
      if (lookahead == 'a') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (lookahead == '-' ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_rgb);
      if (lookahead == 'a') ADVANCE(80);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_rgba);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (lookahead == '-' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_rgba);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_hsl);
      if (lookahead == 'a') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (lookahead == '-' ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_hsl);
      if (lookahead == 'a') ADVANCE(84);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_hsla);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (lookahead == '-' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_hsla);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 33},
  [2] = {.lex_state = 33},
  [3] = {.lex_state = 33},
  [4] = {.lex_state = 33},
  [5] = {.lex_state = 33},
  [6] = {.lex_state = 33},
  [7] = {.lex_state = 33},
  [8] = {.lex_state = 33},
  [9] = {.lex_state = 33},
  [10] = {.lex_state = 33},
  [11] = {.lex_state = 33},
  [12] = {.lex_state = 33},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 33},
  [19] = {.lex_state = 33},
  [20] = {.lex_state = 33},
  [21] = {.lex_state = 33},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 33},
  [24] = {.lex_state = 33},
  [25] = {.lex_state = 33},
  [26] = {.lex_state = 33},
  [27] = {.lex_state = 33},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 33},
  [30] = {.lex_state = 33},
  [31] = {.lex_state = 33},
  [32] = {.lex_state = 33},
  [33] = {.lex_state = 33},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 33},
  [36] = {.lex_state = 33},
  [37] = {.lex_state = 33},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 33},
  [40] = {.lex_state = 33},
  [41] = {.lex_state = 33},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 11},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 37},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 14},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 17},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 18},
  [62] = {.lex_state = 18},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 37},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 18},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 14},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_combinator] = ACTIONS(1),
    [sym_type_selector] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym_class_selector_token1] = ACTIONS(1),
    [anon_sym_POUND2] = ACTIONS(1),
    [aux_sym_pseudo_class_selector_token1] = ACTIONS(1),
    [sym_wildcard_selector] = ACTIONS(1),
    [sym_parent_reference] = ACTIONS(1),
    [sym_property_name] = ACTIONS(1),
    [sym_important] = ACTIONS(1),
    [sym_value_number] = ACTIONS(1),
    [sym_value_string] = ACTIONS(1),
    [anon_sym_rgb] = ACTIONS(1),
    [anon_sym_rgba] = ACTIONS(1),
    [anon_sym_hsl] = ACTIONS(1),
    [anon_sym_hsla] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(63),
    [sym_comment] = STATE(2),
    [sym_variable_declaration] = STATE(2),
    [sym_rule_set] = STATE(2),
    [sym_selector] = STATE(50),
    [sym_class_selector] = STATE(18),
    [sym_id_selector] = STATE(18),
    [sym_variable] = STATE(55),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(7),
    [sym_type_selector] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_POUND2] = ACTIONS(13),
    [sym_wildcard_selector] = ACTIONS(9),
    [sym_parent_reference] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      anon_sym_POUND2,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(50), 1,
      sym_selector,
    STATE(55), 1,
      sym_variable,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(9), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
    STATE(3), 4,
      sym_comment,
      sym_variable_declaration,
      sym_rule_set,
      aux_sym_source_file_repeat1,
  [40] = 11,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(24), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(30), 1,
      anon_sym_DOT,
    ACTIONS(33), 1,
      anon_sym_POUND2,
    ACTIONS(36), 1,
      anon_sym_DOLLAR,
    STATE(50), 1,
      sym_selector,
    STATE(55), 1,
      sym_variable,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(27), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
    STATE(3), 4,
      sym_comment,
      sym_variable_declaration,
      sym_rule_set,
      aux_sym_source_file_repeat1,
  [80] = 10,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      anon_sym_POUND2,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      sym_property_name,
    STATE(51), 1,
      sym_selector,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(9), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
    STATE(7), 4,
      sym_comment,
      sym_rule_set,
      sym_declaration,
      aux_sym_rule_set_repeat1,
  [117] = 10,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      anon_sym_POUND2,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(45), 1,
      sym_property_name,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_selector,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(9), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
    STATE(6), 4,
      sym_comment,
      sym_rule_set,
      sym_declaration,
      aux_sym_rule_set_repeat1,
  [154] = 10,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      anon_sym_POUND2,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      sym_property_name,
    STATE(51), 1,
      sym_selector,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(9), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
    STATE(9), 4,
      sym_comment,
      sym_rule_set,
      sym_declaration,
      aux_sym_rule_set_repeat1,
  [191] = 10,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      anon_sym_POUND2,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(45), 1,
      sym_property_name,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_selector,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(9), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
    STATE(9), 4,
      sym_comment,
      sym_rule_set,
      sym_declaration,
      aux_sym_rule_set_repeat1,
  [228] = 10,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      anon_sym_POUND2,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(45), 1,
      sym_property_name,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_selector,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(9), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
    STATE(11), 4,
      sym_comment,
      sym_rule_set,
      sym_declaration,
      aux_sym_rule_set_repeat1,
  [265] = 10,
    ACTIONS(53), 1,
      anon_sym_POUND,
    ACTIONS(56), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(64), 1,
      anon_sym_DOT,
    ACTIONS(67), 1,
      anon_sym_POUND2,
    ACTIONS(70), 1,
      sym_property_name,
    STATE(51), 1,
      sym_selector,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(61), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
    STATE(9), 4,
      sym_comment,
      sym_rule_set,
      sym_declaration,
      aux_sym_rule_set_repeat1,
  [302] = 10,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      anon_sym_POUND2,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(45), 1,
      sym_property_name,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_selector,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(9), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
    STATE(9), 4,
      sym_comment,
      sym_rule_set,
      sym_declaration,
      aux_sym_rule_set_repeat1,
  [339] = 10,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      anon_sym_POUND2,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(45), 1,
      sym_property_name,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_selector,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(9), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
    STATE(9), 4,
      sym_comment,
      sym_rule_set,
      sym_declaration,
      aux_sym_rule_set_repeat1,
  [376] = 10,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      anon_sym_POUND2,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(45), 1,
      sym_property_name,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_selector,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(9), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
    STATE(10), 4,
      sym_comment,
      sym_rule_set,
      sym_declaration,
      aux_sym_rule_set_repeat1,
  [413] = 8,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(77), 1,
      anon_sym_SEMI,
    ACTIONS(79), 1,
      sym_important,
    ACTIONS(81), 1,
      sym_value_number,
    ACTIONS(83), 1,
      sym_value_string,
    STATE(22), 1,
      sym_variable,
    STATE(14), 3,
      sym_function_call,
      sym_variable_reference,
      aux_sym_value_list_repeat1,
    ACTIONS(85), 4,
      anon_sym_rgb,
      anon_sym_rgba,
      anon_sym_hsl,
      anon_sym_hsla,
  [443] = 7,
    ACTIONS(89), 1,
      sym_value_number,
    ACTIONS(92), 1,
      sym_value_string,
    ACTIONS(98), 1,
      anon_sym_DOLLAR,
    STATE(22), 1,
      sym_variable,
    ACTIONS(87), 2,
      anon_sym_SEMI,
      sym_important,
    STATE(14), 3,
      sym_function_call,
      sym_variable_reference,
      aux_sym_value_list_repeat1,
    ACTIONS(95), 4,
      anon_sym_rgb,
      anon_sym_rgba,
      anon_sym_hsl,
      anon_sym_hsla,
  [471] = 7,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(101), 1,
      sym_value_number,
    ACTIONS(103), 1,
      sym_value_string,
    STATE(22), 1,
      sym_variable,
    STATE(66), 1,
      sym_value_list,
    STATE(13), 3,
      sym_function_call,
      sym_variable_reference,
      aux_sym_value_list_repeat1,
    ACTIONS(85), 4,
      anon_sym_rgb,
      anon_sym_rgba,
      anon_sym_hsl,
      anon_sym_hsla,
  [498] = 7,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(101), 1,
      sym_value_number,
    ACTIONS(103), 1,
      sym_value_string,
    STATE(22), 1,
      sym_variable,
    STATE(60), 1,
      sym_value_list,
    STATE(13), 3,
      sym_function_call,
      sym_variable_reference,
      aux_sym_value_list_repeat1,
    ACTIONS(85), 4,
      anon_sym_rgb,
      anon_sym_rgba,
      anon_sym_hsl,
      anon_sym_hsla,
  [525] = 2,
    ACTIONS(105), 5,
      anon_sym_COLON,
      anon_sym_SEMI,
      sym_important,
      sym_value_number,
      anon_sym_DOLLAR,
    ACTIONS(107), 5,
      sym_value_string,
      anon_sym_rgb,
      anon_sym_rgba,
      anon_sym_hsl,
      anon_sym_hsla,
  [540] = 6,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(109), 1,
      anon_sym_COLON,
    ACTIONS(113), 1,
      sym_combinator,
    STATE(46), 1,
      aux_sym_selector_repeat1,
    ACTIONS(111), 2,
      anon_sym_LBRACE,
      anon_sym_COMMA,
    STATE(19), 3,
      sym_class_selector,
      sym_pseudo_class_selector,
      aux_sym_simple_selector_repeat1,
  [562] = 6,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(109), 1,
      anon_sym_COLON,
    ACTIONS(113), 1,
      sym_combinator,
    STATE(43), 1,
      aux_sym_selector_repeat1,
    ACTIONS(115), 2,
      anon_sym_LBRACE,
      anon_sym_COMMA,
    STATE(37), 3,
      sym_class_selector,
      sym_pseudo_class_selector,
      aux_sym_simple_selector_repeat1,
  [584] = 2,
    ACTIONS(119), 1,
      anon_sym_POUND2,
    ACTIONS(117), 8,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      anon_sym_DOLLAR,
  [598] = 2,
    ACTIONS(123), 1,
      anon_sym_POUND2,
    ACTIONS(121), 8,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      anon_sym_DOLLAR,
  [612] = 2,
    ACTIONS(125), 4,
      anon_sym_SEMI,
      sym_important,
      sym_value_number,
      anon_sym_DOLLAR,
    ACTIONS(127), 5,
      sym_value_string,
      anon_sym_rgb,
      anon_sym_rgba,
      anon_sym_hsl,
      anon_sym_hsla,
  [626] = 2,
    ACTIONS(131), 1,
      anon_sym_POUND2,
    ACTIONS(129), 8,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      anon_sym_DOLLAR,
  [640] = 2,
    ACTIONS(135), 1,
      anon_sym_POUND2,
    ACTIONS(133), 8,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      anon_sym_DOLLAR,
  [654] = 2,
    ACTIONS(139), 1,
      anon_sym_POUND2,
    ACTIONS(137), 8,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      anon_sym_DOLLAR,
  [668] = 2,
    ACTIONS(143), 1,
      anon_sym_POUND2,
    ACTIONS(141), 8,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      anon_sym_DOLLAR,
  [682] = 2,
    ACTIONS(147), 1,
      anon_sym_POUND2,
    ACTIONS(145), 8,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      anon_sym_RBRACE,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      sym_property_name,
  [696] = 2,
    ACTIONS(149), 4,
      anon_sym_SEMI,
      sym_important,
      sym_value_number,
      anon_sym_DOLLAR,
    ACTIONS(151), 5,
      sym_value_string,
      anon_sym_rgb,
      anon_sym_rgba,
      anon_sym_hsl,
      anon_sym_hsla,
  [710] = 2,
    ACTIONS(135), 1,
      anon_sym_POUND2,
    ACTIONS(133), 8,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      anon_sym_RBRACE,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      sym_property_name,
  [724] = 2,
    ACTIONS(123), 1,
      anon_sym_POUND2,
    ACTIONS(121), 8,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      anon_sym_RBRACE,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      sym_property_name,
  [738] = 2,
    ACTIONS(131), 1,
      anon_sym_POUND2,
    ACTIONS(129), 8,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      anon_sym_RBRACE,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      sym_property_name,
  [752] = 2,
    ACTIONS(119), 1,
      anon_sym_POUND2,
    ACTIONS(117), 8,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      anon_sym_RBRACE,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      sym_property_name,
  [766] = 2,
    ACTIONS(143), 1,
      anon_sym_POUND2,
    ACTIONS(141), 8,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
      anon_sym_RBRACE,
      sym_type_selector,
      anon_sym_DOT,
      sym_wildcard_selector,
      sym_parent_reference,
      sym_property_name,
  [780] = 5,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(153), 1,
      anon_sym_POUND2,
    STATE(53), 1,
      sym_selector,
    STATE(18), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(9), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
  [799] = 4,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(109), 1,
      anon_sym_COLON,
    ACTIONS(155), 3,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_combinator,
    STATE(36), 3,
      sym_class_selector,
      sym_pseudo_class_selector,
      aux_sym_simple_selector_repeat1,
  [816] = 4,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(109), 1,
      anon_sym_COLON,
    ACTIONS(157), 3,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_combinator,
    STATE(37), 3,
      sym_class_selector,
      sym_pseudo_class_selector,
      aux_sym_simple_selector_repeat1,
  [833] = 4,
    ACTIONS(159), 1,
      anon_sym_COLON,
    ACTIONS(164), 1,
      anon_sym_DOT,
    ACTIONS(162), 3,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_combinator,
    STATE(37), 3,
      sym_class_selector,
      sym_pseudo_class_selector,
      aux_sym_simple_selector_repeat1,
  [850] = 4,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(153), 1,
      anon_sym_POUND2,
    STATE(35), 2,
      sym_class_selector,
      sym_id_selector,
    ACTIONS(167), 3,
      sym_type_selector,
      sym_wildcard_selector,
      sym_parent_reference,
  [866] = 1,
    ACTIONS(169), 5,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_combinator,
      anon_sym_DOT,
  [874] = 1,
    ACTIONS(171), 5,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_combinator,
      anon_sym_DOT,
  [882] = 1,
    ACTIONS(173), 5,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_combinator,
      anon_sym_DOT,
  [890] = 3,
    ACTIONS(175), 1,
      sym_combinator,
    STATE(42), 1,
      aux_sym_selector_repeat1,
    ACTIONS(155), 2,
      anon_sym_LBRACE,
      anon_sym_COMMA,
  [901] = 3,
    ACTIONS(113), 1,
      sym_combinator,
    STATE(42), 1,
      aux_sym_selector_repeat1,
    ACTIONS(178), 2,
      anon_sym_LBRACE,
      anon_sym_COMMA,
  [912] = 3,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(180), 2,
      anon_sym_COMMA,
      sym_value_number,
  [923] = 3,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(184), 2,
      anon_sym_COMMA,
      sym_value_number,
  [934] = 3,
    ACTIONS(113), 1,
      sym_combinator,
    STATE(42), 1,
      aux_sym_selector_repeat1,
    ACTIONS(115), 2,
      anon_sym_LBRACE,
      anon_sym_COMMA,
  [945] = 2,
    STATE(44), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      sym_value_number,
  [953] = 3,
    ACTIONS(191), 1,
      anon_sym_LBRACE,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_selector_group_repeat1,
  [963] = 3,
    ACTIONS(195), 1,
      anon_sym_LBRACE,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_selector_group_repeat1,
  [973] = 3,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      aux_sym_selector_group_repeat1,
  [983] = 3,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      aux_sym_selector_group_repeat1,
  [993] = 3,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      aux_sym_selector_group_repeat1,
  [1003] = 1,
    ACTIONS(195), 2,
      anon_sym_LBRACE,
      anon_sym_COMMA,
  [1008] = 1,
    ACTIONS(206), 1,
      aux_sym_comment_token1,
  [1012] = 1,
    ACTIONS(208), 1,
      anon_sym_COLON,
  [1016] = 1,
    ACTIONS(210), 1,
      aux_sym_comment_token2,
  [1020] = 1,
    ACTIONS(212), 1,
      anon_sym_SLASH,
  [1024] = 1,
    ACTIONS(214), 1,
      anon_sym_SEMI,
  [1028] = 1,
    ACTIONS(216), 1,
      aux_sym_pseudo_class_selector_token1,
  [1032] = 1,
    ACTIONS(218), 1,
      anon_sym_SEMI,
  [1036] = 1,
    ACTIONS(220), 1,
      aux_sym_class_selector_token1,
  [1040] = 1,
    ACTIONS(222), 1,
      aux_sym_class_selector_token1,
  [1044] = 1,
    ACTIONS(224), 1,
      ts_builtin_sym_end,
  [1048] = 1,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
  [1052] = 1,
    ACTIONS(228), 1,
      aux_sym_comment_token1,
  [1056] = 1,
    ACTIONS(230), 1,
      anon_sym_SEMI,
  [1060] = 1,
    ACTIONS(232), 1,
      anon_sym_SLASH,
  [1064] = 1,
    ACTIONS(234), 1,
      aux_sym_class_selector_token1,
  [1068] = 1,
    ACTIONS(236), 1,
      anon_sym_COLON,
  [1072] = 1,
    ACTIONS(238), 1,
      aux_sym_comment_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 117,
  [SMALL_STATE(6)] = 154,
  [SMALL_STATE(7)] = 191,
  [SMALL_STATE(8)] = 228,
  [SMALL_STATE(9)] = 265,
  [SMALL_STATE(10)] = 302,
  [SMALL_STATE(11)] = 339,
  [SMALL_STATE(12)] = 376,
  [SMALL_STATE(13)] = 413,
  [SMALL_STATE(14)] = 443,
  [SMALL_STATE(15)] = 471,
  [SMALL_STATE(16)] = 498,
  [SMALL_STATE(17)] = 525,
  [SMALL_STATE(18)] = 540,
  [SMALL_STATE(19)] = 562,
  [SMALL_STATE(20)] = 584,
  [SMALL_STATE(21)] = 598,
  [SMALL_STATE(22)] = 612,
  [SMALL_STATE(23)] = 626,
  [SMALL_STATE(24)] = 640,
  [SMALL_STATE(25)] = 654,
  [SMALL_STATE(26)] = 668,
  [SMALL_STATE(27)] = 682,
  [SMALL_STATE(28)] = 696,
  [SMALL_STATE(29)] = 710,
  [SMALL_STATE(30)] = 724,
  [SMALL_STATE(31)] = 738,
  [SMALL_STATE(32)] = 752,
  [SMALL_STATE(33)] = 766,
  [SMALL_STATE(34)] = 780,
  [SMALL_STATE(35)] = 799,
  [SMALL_STATE(36)] = 816,
  [SMALL_STATE(37)] = 833,
  [SMALL_STATE(38)] = 850,
  [SMALL_STATE(39)] = 866,
  [SMALL_STATE(40)] = 874,
  [SMALL_STATE(41)] = 882,
  [SMALL_STATE(42)] = 890,
  [SMALL_STATE(43)] = 901,
  [SMALL_STATE(44)] = 912,
  [SMALL_STATE(45)] = 923,
  [SMALL_STATE(46)] = 934,
  [SMALL_STATE(47)] = 945,
  [SMALL_STATE(48)] = 953,
  [SMALL_STATE(49)] = 963,
  [SMALL_STATE(50)] = 973,
  [SMALL_STATE(51)] = 983,
  [SMALL_STATE(52)] = 993,
  [SMALL_STATE(53)] = 1003,
  [SMALL_STATE(54)] = 1008,
  [SMALL_STATE(55)] = 1012,
  [SMALL_STATE(56)] = 1016,
  [SMALL_STATE(57)] = 1020,
  [SMALL_STATE(58)] = 1024,
  [SMALL_STATE(59)] = 1028,
  [SMALL_STATE(60)] = 1032,
  [SMALL_STATE(61)] = 1036,
  [SMALL_STATE(62)] = 1040,
  [SMALL_STATE(63)] = 1044,
  [SMALL_STATE(64)] = 1048,
  [SMALL_STATE(65)] = 1052,
  [SMALL_STATE(66)] = 1056,
  [SMALL_STATE(67)] = 1060,
  [SMALL_STATE(68)] = 1064,
  [SMALL_STATE(69)] = 1068,
  [SMALL_STATE(70)] = 1072,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_set_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_set_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_set_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_set_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_set_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_set_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_set_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_list, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_list_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_list_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_list_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_list_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_list_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_set, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_set, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_reference, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_reference, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_set, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_set, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_set, 5, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_set, 5, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 3, 0, 0),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_simple_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_simple_selector_repeat1, 2, 0, 0),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_simple_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_selector, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pseudo_class_selector, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_selector, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selector_group_repeat1, 2, 0, 0),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selector_group_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_list, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [224] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tcss(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tcss",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
