/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment_block = 1,
  sym_comment_line = 2,
  anon_sym_COMMA = 3,
  sym_wildcard_selector = 4,
  sym_nesting_selector = 5,
  anon_sym_DOT = 6,
  anon_sym_POUND = 7,
  sym_class_name = 8,
  sym_id_name = 9,
  anon_sym_COLON = 10,
  sym_pseudo_class_name = 11,
  sym_widget_selector = 12,
  sym_combinator = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_SEMI = 16,
  sym_property_name = 17,
  sym_important = 18,
  sym_numeric_value = 19,
  sym_color_value = 20,
  anon_sym_LPAREN = 21,
  anon_sym_RPAREN = 22,
  sym_variable = 23,
  sym_keyword = 24,
  sym_stylesheet = 25,
  sym_selectors = 26,
  sym_selector = 27,
  sym__selector_unit = 28,
  sym_class_selector = 29,
  sym_id_selector = 30,
  sym_pseudo_class_selector = 31,
  sym_rule_set = 32,
  sym_block = 33,
  sym_declaration = 34,
  sym__value = 35,
  sym_function_call = 36,
  sym_variable_definition = 37,
  aux_sym_stylesheet_repeat1 = 38,
  aux_sym_selectors_repeat1 = 39,
  aux_sym_selector_repeat1 = 40,
  aux_sym_block_repeat1 = 41,
  aux_sym_declaration_repeat1 = 42,
  aux_sym_function_call_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment_block] = "comment_block",
  [sym_comment_line] = "comment_line",
  [anon_sym_COMMA] = ",",
  [sym_wildcard_selector] = "wildcard_selector",
  [sym_nesting_selector] = "nesting_selector",
  [anon_sym_DOT] = ".",
  [anon_sym_POUND] = "#",
  [sym_class_name] = "class_name",
  [sym_id_name] = "id_name",
  [anon_sym_COLON] = ":",
  [sym_pseudo_class_name] = "pseudo_class_name",
  [sym_widget_selector] = "widget_selector",
  [sym_combinator] = "combinator",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [sym_property_name] = "property_name",
  [sym_important] = "important",
  [sym_numeric_value] = "numeric_value",
  [sym_color_value] = "color_value",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_variable] = "variable",
  [sym_keyword] = "keyword",
  [sym_stylesheet] = "stylesheet",
  [sym_selectors] = "selectors",
  [sym_selector] = "selector",
  [sym__selector_unit] = "_selector_unit",
  [sym_class_selector] = "class_selector",
  [sym_id_selector] = "id_selector",
  [sym_pseudo_class_selector] = "pseudo_class_selector",
  [sym_rule_set] = "rule_set",
  [sym_block] = "block",
  [sym_declaration] = "declaration",
  [sym__value] = "_value",
  [sym_function_call] = "function_call",
  [sym_variable_definition] = "variable_definition",
  [aux_sym_stylesheet_repeat1] = "stylesheet_repeat1",
  [aux_sym_selectors_repeat1] = "selectors_repeat1",
  [aux_sym_selector_repeat1] = "selector_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_declaration_repeat1] = "declaration_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment_block] = sym_comment_block,
  [sym_comment_line] = sym_comment_line,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_wildcard_selector] = sym_wildcard_selector,
  [sym_nesting_selector] = sym_nesting_selector,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_class_name] = sym_class_name,
  [sym_id_name] = sym_id_name,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_pseudo_class_name] = sym_pseudo_class_name,
  [sym_widget_selector] = sym_widget_selector,
  [sym_combinator] = sym_combinator,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_property_name] = sym_property_name,
  [sym_important] = sym_important,
  [sym_numeric_value] = sym_numeric_value,
  [sym_color_value] = sym_color_value,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_variable] = sym_variable,
  [sym_keyword] = sym_keyword,
  [sym_stylesheet] = sym_stylesheet,
  [sym_selectors] = sym_selectors,
  [sym_selector] = sym_selector,
  [sym__selector_unit] = sym__selector_unit,
  [sym_class_selector] = sym_class_selector,
  [sym_id_selector] = sym_id_selector,
  [sym_pseudo_class_selector] = sym_pseudo_class_selector,
  [sym_rule_set] = sym_rule_set,
  [sym_block] = sym_block,
  [sym_declaration] = sym_declaration,
  [sym__value] = sym__value,
  [sym_function_call] = sym_function_call,
  [sym_variable_definition] = sym_variable_definition,
  [aux_sym_stylesheet_repeat1] = aux_sym_stylesheet_repeat1,
  [aux_sym_selectors_repeat1] = aux_sym_selectors_repeat1,
  [aux_sym_selector_repeat1] = aux_sym_selector_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_declaration_repeat1] = aux_sym_declaration_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_block] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_wildcard_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_nesting_selector] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_class_name] = {
    .visible = true,
    .named = true,
  },
  [sym_id_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_pseudo_class_name] = {
    .visible = true,
    .named = true,
  },
  [sym_widget_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_combinator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym_important] = {
    .visible = true,
    .named = true,
  },
  [sym_numeric_value] = {
    .visible = true,
    .named = true,
  },
  [sym_color_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_stylesheet] = {
    .visible = true,
    .named = true,
  },
  [sym_selectors] = {
    .visible = true,
    .named = true,
  },
  [sym_selector] = {
    .visible = true,
    .named = true,
  },
  [sym__selector_unit] = {
    .visible = false,
    .named = true,
  },
  [sym_class_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_id_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_pseudo_class_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_rule_set] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_stylesheet_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selectors_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '!', 13,
        '#', 36,
        '$', 26,
        '&', 34,
        '(', 59,
        ')', 60,
        '*', 33,
        ',', 32,
        '.', 35,
        '/', 8,
        ':', 41,
        ';', 47,
        '>', 44,
        '{', 45,
        '}', 46,
        '-', 39,
        '_', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(39);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '!', 13,
        '#', 2,
        '$', 26,
        '(', 59,
        ')', 60,
        ',', 32,
        '.', 23,
        '/', 8,
        ';', 47,
        '+', 11,
        '-', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '!', 13,
        '#', 2,
        '$', 26,
        ')', 60,
        ',', 32,
        '.', 23,
        '/', 8,
        ';', 47,
        '+', 11,
        '-', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '/') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '/') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '/') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 22:
      if (lookahead == 'h' ||
          lookahead == 'w') ADVANCE(50);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 27:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '!', 13,
        '#', 36,
        '$', 26,
        '&', 34,
        ')', 60,
        '*', 33,
        ',', 32,
        '.', 35,
        '/', 8,
        ':', 41,
        ';', 47,
        '>', 44,
        '{', 45,
        '}', 46,
        '-', 39,
        '_', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(39);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '#', 36,
        '$', 26,
        '&', 34,
        '*', 33,
        ',', 32,
        '.', 35,
        '/', 8,
        ':', 41,
        '>', 44,
        '{', 45,
        '}', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(43);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment_block);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_wildcard_selector);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_nesting_selector);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_class_name);
      if (lookahead == '_') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(39);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_class_name);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(39);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_class_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_id_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_pseudo_class_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_widget_selector);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_combinator);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_property_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_important);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_numeric_value);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_numeric_value);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'f') ADVANCE(19);
      if (lookahead == 'v') ADVANCE(22);
      if (lookahead == '%' ||
          lookahead == 'h' ||
          lookahead == 'w') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_numeric_value);
      if (lookahead == 'f') ADVANCE(19);
      if (lookahead == 'v') ADVANCE(22);
      if (lookahead == '%' ||
          lookahead == 'h' ||
          lookahead == 'w') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_color_value);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_color_value);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_color_value);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_color_value);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_color_value);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_color_value);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 28},
  [3] = {.lex_state = 28},
  [4] = {.lex_state = 28},
  [5] = {.lex_state = 28},
  [6] = {.lex_state = 28},
  [7] = {.lex_state = 28},
  [8] = {.lex_state = 28},
  [9] = {.lex_state = 28},
  [10] = {.lex_state = 28},
  [11] = {.lex_state = 28},
  [12] = {.lex_state = 28},
  [13] = {.lex_state = 28},
  [14] = {.lex_state = 28},
  [15] = {.lex_state = 28},
  [16] = {.lex_state = 28},
  [17] = {.lex_state = 28},
  [18] = {.lex_state = 28},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 28},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 28},
  [30] = {.lex_state = 28},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment_block] = ACTIONS(3),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_wildcard_selector] = ACTIONS(1),
    [sym_nesting_selector] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_class_name] = ACTIONS(1),
    [sym_id_name] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_pseudo_class_name] = ACTIONS(1),
    [sym_widget_selector] = ACTIONS(1),
    [sym_combinator] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_property_name] = ACTIONS(1),
    [sym_important] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_stylesheet] = STATE(46),
    [sym_selectors] = STATE(38),
    [sym_selector] = STATE(35),
    [sym__selector_unit] = STATE(8),
    [sym_class_selector] = STATE(8),
    [sym_id_selector] = STATE(8),
    [sym_pseudo_class_selector] = STATE(8),
    [sym_rule_set] = STATE(2),
    [sym_variable_definition] = STATE(2),
    [aux_sym_stylesheet_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment_block] = ACTIONS(3),
    [sym_comment_line] = ACTIONS(3),
    [sym_wildcard_selector] = ACTIONS(7),
    [sym_nesting_selector] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(13),
    [sym_widget_selector] = ACTIONS(7),
    [sym_variable] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      sym_variable,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(35), 1,
      sym_selector,
    STATE(38), 1,
      sym_selectors,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(7), 3,
      sym_wildcard_selector,
      sym_nesting_selector,
      sym_widget_selector,
    STATE(4), 3,
      sym_rule_set,
      sym_variable_definition,
      aux_sym_stylesheet_repeat1,
    STATE(8), 4,
      sym__selector_unit,
      sym_class_selector,
      sym_id_selector,
      sym_pseudo_class_selector,
  [42] = 11,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      sym_property_name,
    STATE(35), 1,
      sym_selector,
    STATE(38), 1,
      sym_selectors,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(7), 3,
      sym_wildcard_selector,
      sym_nesting_selector,
      sym_widget_selector,
    STATE(5), 3,
      sym_rule_set,
      sym_declaration,
      aux_sym_block_repeat1,
    STATE(8), 4,
      sym__selector_unit,
      sym_class_selector,
      sym_id_selector,
      sym_pseudo_class_selector,
  [84] = 11,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(31), 1,
      anon_sym_POUND,
    ACTIONS(34), 1,
      anon_sym_COLON,
    ACTIONS(37), 1,
      sym_variable,
    STATE(35), 1,
      sym_selector,
    STATE(38), 1,
      sym_selectors,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(25), 3,
      sym_wildcard_selector,
      sym_nesting_selector,
      sym_widget_selector,
    STATE(4), 3,
      sym_rule_set,
      sym_variable_definition,
      aux_sym_stylesheet_repeat1,
    STATE(8), 4,
      sym__selector_unit,
      sym_class_selector,
      sym_id_selector,
      sym_pseudo_class_selector,
  [126] = 11,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(21), 1,
      sym_property_name,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    STATE(35), 1,
      sym_selector,
    STATE(38), 1,
      sym_selectors,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(7), 3,
      sym_wildcard_selector,
      sym_nesting_selector,
      sym_widget_selector,
    STATE(6), 3,
      sym_rule_set,
      sym_declaration,
      aux_sym_block_repeat1,
    STATE(8), 4,
      sym__selector_unit,
      sym_class_selector,
      sym_id_selector,
      sym_pseudo_class_selector,
  [168] = 11,
    ACTIONS(45), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_POUND,
    ACTIONS(51), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_RBRACE,
    ACTIONS(56), 1,
      sym_property_name,
    STATE(35), 1,
      sym_selector,
    STATE(38), 1,
      sym_selectors,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(42), 3,
      sym_wildcard_selector,
      sym_nesting_selector,
      sym_widget_selector,
    STATE(6), 3,
      sym_rule_set,
      sym_declaration,
      aux_sym_block_repeat1,
    STATE(8), 4,
      sym__selector_unit,
      sym_class_selector,
      sym_id_selector,
      sym_pseudo_class_selector,
  [210] = 8,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(63), 1,
      sym_combinator,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(59), 2,
      anon_sym_COMMA,
      anon_sym_LBRACE,
    ACTIONS(61), 3,
      sym_wildcard_selector,
      sym_nesting_selector,
      sym_widget_selector,
    STATE(9), 5,
      sym__selector_unit,
      sym_class_selector,
      sym_id_selector,
      sym_pseudo_class_selector,
      aux_sym_selector_repeat1,
  [243] = 8,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(63), 1,
      sym_combinator,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(65), 2,
      anon_sym_COMMA,
      anon_sym_LBRACE,
    ACTIONS(67), 3,
      sym_wildcard_selector,
      sym_nesting_selector,
      sym_widget_selector,
    STATE(7), 5,
      sym__selector_unit,
      sym_class_selector,
      sym_id_selector,
      sym_pseudo_class_selector,
      aux_sym_selector_repeat1,
  [276] = 8,
    ACTIONS(74), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      anon_sym_POUND,
    ACTIONS(80), 1,
      anon_sym_COLON,
    ACTIONS(83), 1,
      sym_combinator,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(69), 2,
      anon_sym_COMMA,
      anon_sym_LBRACE,
    ACTIONS(71), 3,
      sym_wildcard_selector,
      sym_nesting_selector,
      sym_widget_selector,
    STATE(9), 5,
      sym__selector_unit,
      sym_class_selector,
      sym_id_selector,
      sym_pseudo_class_selector,
      aux_sym_selector_repeat1,
  [309] = 7,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_COLON,
    STATE(39), 1,
      sym_selector,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(7), 3,
      sym_wildcard_selector,
      sym_nesting_selector,
      sym_widget_selector,
    STATE(8), 4,
      sym__selector_unit,
      sym_class_selector,
      sym_id_selector,
      sym_pseudo_class_selector,
  [337] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(86), 3,
      sym_wildcard_selector,
      sym_nesting_selector,
      sym_widget_selector,
    STATE(15), 4,
      sym__selector_unit,
      sym_class_selector,
      sym_id_selector,
      sym_pseudo_class_selector,
  [362] = 3,
    ACTIONS(90), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(88), 9,
      ts_builtin_sym_end,
      sym_wildcard_selector,
      sym_nesting_selector,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_widget_selector,
      anon_sym_RBRACE,
      sym_property_name,
      sym_variable,
  [381] = 3,
    ACTIONS(94), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(92), 9,
      ts_builtin_sym_end,
      sym_wildcard_selector,
      sym_nesting_selector,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_widget_selector,
      anon_sym_RBRACE,
      sym_property_name,
      sym_variable,
  [400] = 3,
    ACTIONS(98), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(96), 9,
      ts_builtin_sym_end,
      sym_wildcard_selector,
      sym_nesting_selector,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_widget_selector,
      anon_sym_RBRACE,
      sym_property_name,
      sym_variable,
  [419] = 3,
    ACTIONS(100), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(69), 8,
      anon_sym_COMMA,
      sym_wildcard_selector,
      sym_nesting_selector,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_widget_selector,
      sym_combinator,
      anon_sym_LBRACE,
  [437] = 3,
    ACTIONS(104), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(102), 8,
      anon_sym_COMMA,
      sym_wildcard_selector,
      sym_nesting_selector,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_widget_selector,
      sym_combinator,
      anon_sym_LBRACE,
  [455] = 3,
    ACTIONS(108), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(106), 8,
      anon_sym_COMMA,
      sym_wildcard_selector,
      sym_nesting_selector,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_widget_selector,
      sym_combinator,
      anon_sym_LBRACE,
  [473] = 3,
    ACTIONS(112), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(110), 8,
      anon_sym_COMMA,
      sym_wildcard_selector,
      sym_nesting_selector,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_widget_selector,
      sym_combinator,
      anon_sym_LBRACE,
  [491] = 3,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(114), 8,
      anon_sym_COMMA,
      anon_sym_SEMI,
      sym_important,
      sym_numeric_value,
      sym_color_value,
      anon_sym_RPAREN,
      sym_variable,
      sym_keyword,
  [509] = 6,
    ACTIONS(118), 1,
      anon_sym_SEMI,
    ACTIONS(120), 1,
      sym_important,
    ACTIONS(124), 1,
      sym_keyword,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(122), 3,
      sym_numeric_value,
      sym_color_value,
      sym_variable,
    STATE(21), 3,
      sym__value,
      sym_function_call,
      aux_sym_declaration_repeat1,
  [533] = 5,
    ACTIONS(131), 1,
      sym_keyword,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(126), 2,
      anon_sym_SEMI,
      sym_important,
    ACTIONS(128), 3,
      sym_numeric_value,
      sym_color_value,
      sym_variable,
    STATE(21), 3,
      sym__value,
      sym_function_call,
      aux_sym_declaration_repeat1,
  [555] = 5,
    ACTIONS(124), 1,
      sym_keyword,
    ACTIONS(134), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(122), 3,
      sym_numeric_value,
      sym_color_value,
      sym_variable,
    STATE(21), 3,
      sym__value,
      sym_function_call,
      aux_sym_declaration_repeat1,
  [576] = 6,
    ACTIONS(124), 1,
      sym_keyword,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    STATE(33), 2,
      sym__value,
      sym_function_call,
    ACTIONS(136), 3,
      sym_numeric_value,
      sym_color_value,
      sym_variable,
  [599] = 6,
    ACTIONS(124), 1,
      sym_keyword,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    STATE(33), 2,
      sym__value,
      sym_function_call,
    ACTIONS(136), 3,
      sym_numeric_value,
      sym_color_value,
      sym_variable,
  [622] = 2,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(142), 8,
      anon_sym_COMMA,
      anon_sym_SEMI,
      sym_important,
      sym_numeric_value,
      sym_color_value,
      anon_sym_RPAREN,
      sym_variable,
      sym_keyword,
  [637] = 3,
    ACTIONS(146), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(144), 7,
      ts_builtin_sym_end,
      sym_wildcard_selector,
      sym_nesting_selector,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_widget_selector,
      sym_variable,
  [654] = 2,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(148), 8,
      anon_sym_COMMA,
      anon_sym_SEMI,
      sym_important,
      sym_numeric_value,
      sym_color_value,
      anon_sym_RPAREN,
      sym_variable,
      sym_keyword,
  [669] = 6,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
    ACTIONS(155), 1,
      sym_keyword,
    STATE(28), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    STATE(33), 2,
      sym__value,
      sym_function_call,
    ACTIONS(150), 3,
      sym_numeric_value,
      sym_color_value,
      sym_variable,
  [692] = 3,
    ACTIONS(160), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(158), 7,
      sym_wildcard_selector,
      sym_nesting_selector,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_widget_selector,
      anon_sym_RBRACE,
      sym_property_name,
  [709] = 3,
    ACTIONS(164), 1,
      anon_sym_POUND,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(162), 7,
      sym_wildcard_selector,
      sym_nesting_selector,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_widget_selector,
      anon_sym_RBRACE,
      sym_property_name,
  [726] = 4,
    ACTIONS(124), 1,
      sym_keyword,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(166), 3,
      sym_numeric_value,
      sym_color_value,
      sym_variable,
    STATE(22), 3,
      sym__value,
      sym_function_call,
      aux_sym_declaration_repeat1,
  [744] = 4,
    ACTIONS(124), 1,
      sym_keyword,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(168), 3,
      sym_numeric_value,
      sym_color_value,
      sym_variable,
    STATE(20), 3,
      sym__value,
      sym_function_call,
      aux_sym_declaration_repeat1,
  [762] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(172), 5,
      sym_numeric_value,
      sym_color_value,
      anon_sym_RPAREN,
      sym_variable,
      sym_keyword,
  [777] = 2,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(153), 5,
      sym_numeric_value,
      sym_color_value,
      anon_sym_RPAREN,
      sym_variable,
      sym_keyword,
  [789] = 4,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    STATE(37), 1,
      aux_sym_selectors_repeat1,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
  [803] = 4,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      aux_sym_selectors_repeat1,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
  [817] = 4,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      aux_sym_selectors_repeat1,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
  [831] = 3,
    ACTIONS(185), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
  [842] = 2,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
    ACTIONS(181), 2,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [851] = 2,
    ACTIONS(187), 1,
      sym_pseudo_class_name,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
  [859] = 2,
    ACTIONS(189), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
  [867] = 2,
    ACTIONS(191), 1,
      sym_id_name,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
  [875] = 2,
    ACTIONS(193), 1,
      sym_class_name,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
  [883] = 2,
    ACTIONS(195), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
  [891] = 2,
    ACTIONS(197), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
  [899] = 2,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment_block,
      sym_comment_line,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 126,
  [SMALL_STATE(6)] = 168,
  [SMALL_STATE(7)] = 210,
  [SMALL_STATE(8)] = 243,
  [SMALL_STATE(9)] = 276,
  [SMALL_STATE(10)] = 309,
  [SMALL_STATE(11)] = 337,
  [SMALL_STATE(12)] = 362,
  [SMALL_STATE(13)] = 381,
  [SMALL_STATE(14)] = 400,
  [SMALL_STATE(15)] = 419,
  [SMALL_STATE(16)] = 437,
  [SMALL_STATE(17)] = 455,
  [SMALL_STATE(18)] = 473,
  [SMALL_STATE(19)] = 491,
  [SMALL_STATE(20)] = 509,
  [SMALL_STATE(21)] = 533,
  [SMALL_STATE(22)] = 555,
  [SMALL_STATE(23)] = 576,
  [SMALL_STATE(24)] = 599,
  [SMALL_STATE(25)] = 622,
  [SMALL_STATE(26)] = 637,
  [SMALL_STATE(27)] = 654,
  [SMALL_STATE(28)] = 669,
  [SMALL_STATE(29)] = 692,
  [SMALL_STATE(30)] = 709,
  [SMALL_STATE(31)] = 726,
  [SMALL_STATE(32)] = 744,
  [SMALL_STATE(33)] = 762,
  [SMALL_STATE(34)] = 777,
  [SMALL_STATE(35)] = 789,
  [SMALL_STATE(36)] = 803,
  [SMALL_STATE(37)] = 817,
  [SMALL_STATE(38)] = 831,
  [SMALL_STATE(39)] = 842,
  [SMALL_STATE(40)] = 851,
  [SMALL_STATE(41)] = 859,
  [SMALL_STATE(42)] = 867,
  [SMALL_STATE(43)] = 875,
  [SMALL_STATE(44)] = 883,
  [SMALL_STATE(45)] = 891,
  [SMALL_STATE(46)] = 899,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stylesheet, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stylesheet, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_stylesheet_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stylesheet_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stylesheet_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stylesheet_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stylesheet_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stylesheet_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_set, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_set, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_selector, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id_selector, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pseudo_class_selector, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pseudo_class_selector, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_selector, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_selector, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 4, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_definition, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 1),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 4, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 5, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 5, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selectors, 1, 0, 0),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selectors_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selectors_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selectors, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [199] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tcss(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tcss",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
